 "use client";
import {useState} from "react";
export default function Home(){
 const [image,setImage]=useState(""),[video,setVideo]=useState(""),[prompt,setPrompt]=useState("No distortion, the character's movements are consistent with the video."),[orientation,setOrientation]=useState("video"),[quality,setQuality]=useState("pro"),[task,setTask]=useState(""),[state,setState]=useState(""),[result,setResult]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function generate(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult("");setTask("");setState("Enviando tarefa…");
 try{const r=await fetch("/api/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image,video,prompt,orientation,quality})});const d=await r.json();if(!r.ok)throw Error(d.error||"Falha ao criar tarefa");setTask(d.taskId);setState("Tarefa criada. Aguardando geração…");let done=false;for(let i=0;i<90&&!done;i++){await new Promise(res=>setTimeout(res,4000));const s=await fetch("/api/status?taskId="+encodeURIComponent(d.taskId));const x=await s.json();if(!s.ok)throw Error(x.error||"Falha ao consultar tarefa");const data=x.data||{};setState(data.state||"Processando…");if(data.state==="success"){const parsed=typeof data.resultJson==="string"?JSON.parse(data.resultJson):data.resultJson;setResult(parsed?.resultUrls?.[0]||"");done=true;}else if(data.state==="fail"){throw Error(data.failMsg||"A geração falhou");}}if(!done)setState("Ainda processando. Atualize o status mais tarde.");}
 catch(err){setError(err instanceof Error?err.message:"Erro inesperado");setState("");}finally{setBusy(false)}}
 return <main><header><div className="brand">◈ <span>Motion Control</span></div><span className="tag">Kling 3.0</span></header><section className="hero"><p className="eyebrow">AI VIDEO WORKSPACE</p><h1>Dê movimento<br/><em>à sua imagem.</em></h1><p className="sub">Envie uma imagem e um vídeo de referência. O Kling transfere os movimentos para o personagem.</p></section>
 <form onSubmit={generate} className="panel"><div className="fields"><label>Imagem de referência <small>URL pública JPG ou PNG · até 10 MB</small><input type="url" required placeholder="https://…/imagem.png" value={image} onChange={e=>setImage(e.target.value)}/></label><label>Vídeo de movimento <small>URL pública MP4 ou MOV · até 100 MB</small><input type="url" required placeholder="https://…/referencia.mp4" value={video} onChange={e=>setVideo(e.target.value)}/></label></div><label>Prompt <small>Opcional · até 2500 caracteres</small><textarea maxLength={2500} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3}/></label><div className="options"><label>Orientação<select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="video">Seguir orientação do vídeo (até 30s)</option><option value="image">Seguir orientação da imagem (até 10s)</option></select></label><label>Resolução<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="pro">1080p · Pro</option><option value="std">720p · Standard</option></select></label></div><button disabled={busy}>{busy?"Gerando…":"Gerar vídeo"}</button>{error&&<p className="error">{error}</p>}{state&&<div className="status"><b>Status:</b> {state}{task&&<small>ID: {task}</small>}</div>}{result&&<div className="result"><video src={result} controls playsInline/><a href={result} target="_blank" rel="noreferrer">Abrir ou baixar vídeo ↗</a></div>}</form><footer>Motion Control Studio · A geração é processada pela API Kie.ai.</footer></main>
}